name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # Required to push files

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake-dark.svg
          # Modified colors to match the image pattern
          color_snake: "#1EB980"  # Bright green for the snake
          # Multiple shades of green from brightest to darkest
          color_dots: |
            #1EB980,#149261,#0B6B47,#06442C,#1A1B1E
          background: "#1A1B1E"  # Dark background matching image

      - name: Push Snake Animation to Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
